module.exports = [
new Player(1, "Rohit Sharma", "MI", "Indian"), 
new Player(2, "Jasprit Bumrah", "MI", "Indian"), 
new Player(3, "Hardik Pandya", "MI", "Indian", ), 
new Player(4, "Krunal Pandya", "MI", "Indian"), 
new Player(5, "Kieron Pollard ", "MI", "overseas", ), 
new Player(6, "Evin Lewis ", "MI", "overseas"), 
new Player(7, "Suryakumar Yadav", "MI", "Indian"), 
new Player(8, "Siddhesh Lad", "MI", "Indian"), 
new Player(9, "Mayank Markande", "MI", "Indian"), 
new Player(10, "Anukul Sudhakar Roy", "MI", "Indian"), 
new Player(11, "Jason Behrendorff ", "MI", "overseas"), 
new Player(12, "Rahul Chahar", "MI", "Indian"), 
new Player(13, "Ben Cutting ", "MI", "overseas"), 
new Player(14, "Aditya Tare", "MI", "Indian"), 
new Player(15, "Ishan Kishan", "MI", "Indian"), 
new Player(16, "Rasikh Salam", "MI", "Indian"), 
new Player(17, "Anmolpreet Singh", "MI", "Indian"), 
new Player(18, "Yuvraj Singh", "MI", "Indian"), 
new Player(19, "Barinder Sran", "MI", "Indian"), 
new Player(20, "Lasith Malinga ", "MI", "overseas"), 
new Player(21, "Adam Milne ", "MI", "overseas"), 
new Player(22, "Mitchell McClenaghan ", "MI", "overseas"), 
new Player(23, "Pankaj Jaiswal", "MI", "Indian"), 
new Player(24, "Quinton de Kock ", "MI", "overseas"), 

new Player(25, "MS Dhoni", "CSK", "Indian"), 
new Player(26, "Suresh Raina", "CSK", "Indian"), 
new Player(27, "Ravindra Jadeja", "CSK", "Indian"), 
new Player(28, "Faf du Plessis ", "CSK", "overseas"), 
new Player(29, "Dwayne Bravo ", "CSK", "overseas"), 
new Player(30, "Chaitanya Bishnoi", "CSK", "Indian"), 
new Player(31, "Dhruv Shorey", "CSK", "Indian", ), 
new Player(32, "Murali Vijay", "CSK", "Indian", ), 
new Player(33, "Kedar Jadhav", "CSK", "Indian", ), 
new Player(34, "Shane Watson ", "CSK", "overseas", ), 
new Player(35, "Harbhajan Singh", "CSK", "Indian", ), 
new Player(36, "Deepak Chahar", "CSK", "Indian", ), 
new Player(37, "Lungisani Ngidi ", "CSK", "overseas", ), 
new Player(38, "Monu Kumar", "CSK", "Indian", ), 
new Player(39, "Shardul Thakur", "CSK", "Indian", ), 
new Player(40, "KM Asif", "CSK", "Indian", ), 
new Player(41, "Imran Tahir ", "CSK", "overseas", ), 
new Player(42, "Mitchell Santner ", "CSK", "overseas", ), 
new Player(43, "Karn Sharma", "CSK", "Indian", ), 
new Player(44, "N Jagadeesan", "CSK", "Indian", ), 
new Player(45, "Ambati Rayudu", "CSK", "Indian", ), 
new Player(46, "Sam Billings ", "CSK", "overseas", ), 
new Player(47, "Ruturaj Gaikwad", "CSK", "Indian", ), 
new Player(48, "Mohit Sharma", "CSK", "Indian", ), 
new Player(49, "David Willey ", "CSK", "overseas", )
,
new Player(50, "Virat Kohli", "RCB", "Indian", ), 
new Player(51, "AB de Villiers ", "RCB", "overseas", ), 
new Player(52, "Yuzvendra Chahal", "RCB", "Indian", ), 
new Player(53, "Pawan Negi", "RCB", "Indian", ), 
new Player(54, "Moeen Ali ", "RCB", "overseas", ), 
new Player(55, "Colin de Grandhomme ", "RCB", "overseas", ), 
new Player(56, "Washington Sundar", "RCB", "Indian", ), 
new Player(57, "Nathan Coulter-Nile ", "RCB", "overseas", ), 
new Player(58, "Mohammed Siraj", "RCB", "Indian", ), 
new Player(59, "Navdeep Saini", "RCB", "Indian", ), 
new Player(60, "Kulwant Khejroliya", "RCB", "Indian", ), 
new Player(61, "Tim Southee ", "RCB", "overseas", ), 
new Player(62, "Umesh Yadav", "RCB", "Indian", ), 
new Player(63, "Parthiv Patel", "RCB", "Indian", ), 
new Player(64, "Prayas Barman", "RCB", "Indian", ), 
new Player(65, "Himmat Singh", "RCB", "Indian", ), 
new Player(66, "Akshdeep Nath", "RCB", "Indian", ), 
new Player(67, "Shivam Dube", "RCB", "Indian", ), 
new Player(68, "Devdutt Padikkal", "RCB", "Indian", ), 
new Player(69, "Gurkeerat Singh Mann", "RCB", "Indian", ), 
new Player(70, "Shimron Hetmyer ", "RCB", "overseas", ), 
new Player(71, "Milind Kumar", "RCB", "Indian", ), 
new Player(72, "Heinrich Klaasen ", "RCB", "overseas", ), 
new Player(73, "Marcus Stoinis ", "RCB", "overseas", )
, 
new Player(74, "Shreyas Iyer", "DC", "Indian", ), 
new Player(75, "Shikhar Dhawan", "DC", "Indian", ), 
new Player(76, "Prithvi Shaw", "DC", "Indian", ), 
new Player(77, "Colin Ingram ", "DC", "overseas", ), 
new Player(78, "Manjot Kalra", "DC", "Indian", ), 
new Player(79, "Jalaj Saxena", "DC", "Indian", ), 
new Player(80, "Sherfane Rutherford ", "DC", "overseas", ), 
new Player(81, "Hanuma Vihari", "DC", "Indian", ), 
new Player(82, "Colin Munro ", "DC", "overseas", ), 
new Player(83, "Ishant Sharma", "DC", "Indian", ), 
new Player(84, "Nathu Singh", "DC", "Indian", ), 
new Player(85, "Trent Boult ", "DC", "overseas", ), 
new Player(86, "Sandeep Lamichhane ", "DC", "overseas", ), 
new Player(87, "Kagiso Rabada ", "DC", "overseas", ), 
new Player(88, "Amit Mishra", "DC", "Indian", ), 
new Player(89, "Avesh Khan", "DC", "Indian", ), 
new Player(90, "Harshal Patel", "DC", "Indian", ), 
new Player(91, "Rahul Tewatia", "DC", "Indian", ), 
new Player(92, "Jayant Yadav", "DC", "Indian", ), 
new Player(93, "Bandaru Ayyappa", "DC", "Indian", ), 
new Player(94, "Keemo Paul ", "DC", "overseas", ), 
new Player(95, "Axar Patel", "DC", "Indian", ), 
new Player(96, "Chris Morris ", "DC", "overseas", ), 
new Player(97, "Ankush Bains", "DC", "Indian", ), 
new Player(98, "Rishabh Pant", "DC", "Indian", )
, 
new Player(99, "Andre Russell ", "KKR", "overseas", ), 
new Player(100, "Sunil Narine ", "KKR", "overseas", ), 
new Player(101, "Kuldeep Yadav", "KKR", "Indian", ), 
new Player(102, "Piyush Chawla", "KKR", "Indian", ), 
new Player(103, "Robin Uthappa", "KKR", "Indian", ), 
new Player(104, "Nitish Rana", "KKR", "Indian", ), 
new Player(105, "Shubman Gill", "KKR", "Indian", ), 
new Player(106, "Rinku Singh", "KKR", "Indian", ), 
new Player(107, "Chris Lynn ", "KKR", "overseas", ), 
new Player(108, "Kamlesh Nagarkoti", "KKR", "Indian", ), 
new Player(109, "Shivam Mavi", "KKR", "Indian", ), 
new Player(110, "Dinesh Karthik", "KKR", "Indian", ), 
new Player(111, "Nikhil Naik", "KKR", "Indian", ), 
new Player(112, "Joe Denly ", "KKR", "overseas", ), 
new Player(113, "Shrikant Mundhe", "KKR", "Indian", ), 
new Player(114, "Anrich Nortje ", "KKR", "overseas", ), 
new Player(115, "Harry Gurney ", "KKR", "overseas", ), 
new Player(116, "Lockie Ferguson ", "KKR", "overseas", ), 
new Player(117, "Yarra Prithviraj", "KKR", "Indian", ), 
new Player(118, "Carlos Brathwaite ", "KKR", "overseas", ), 
new Player(119, "Prasidh Krishna", "KKR", "Indian", )
,
new Player(120, "Steven Smith ", "RR", "overseas", ), 
new Player(121, "Ajinkya Rahane", "RR", "Indian", ), 
new Player(122, "Dhawal Kulkarni", "RR", "Indian", ), 
new Player(123, "Aryaman Birla", "RR", "Indian", ), 
new Player(124, "Rahul Tripathi", "RR", "Indian", ), 
new Player(125, "Stuart Binny", "RR", "Indian", ), 
new Player(126, "Mahipal Lomror", "RR", "Indian", ), 
new Player(127, "Jaydev Unadkat", "RR", "Indian", ), 
new Player(128, "S Midhun", "RR", "Indian", ), 
new Player(129, "Shreyas Gopal", "RR", "Indian", ), 
new Player(130, "Krishnappa Gowtham", "RR", "Indian", ), 
new Player(131, "Jofra Archer ", "RR", "overseas", ), 
new Player(132, "Ben Stokes ", "RR", "overseas", ), 
new Player(133, "Jos Buttler ", "RR", "overseas", ), 
new Player(134, "Prashant Chopra", "RR", "Indian", ), 
new Player(135, "Sanju Samson", "RR", "Indian", ), 
new Player(136, "Shashank Singh", "RR", "Indian", ), 
new Player(137, "Riyan Parag", "RR", "Indian", ), 
new Player(138, "Liam Livingstone ", "RR", "overseas", ), 
new Player(139, "Manan Vohra", "RR", "Indian", ), 
new Player(140, "Shubham Ranjane", "RR", "Indian", ), 
new Player(141, "Ashton Turner ", "RR", "overseas", ), 
new Player(142, "Varun Aaron", "RR", "Indian", ), 
new Player(143, "Oshane Thomas ", "RR", "overseas", ), 
new Player(144, "Ish Sodhi ", "RR", "overseas", )
, 
new Player(145, "David Miller ", "KXIP", "overseas", ), 
new Player(146, "Mayank Agarwal", "KXIP", "Indian", ), 
new Player(147, "Karun Nair", "KXIP", "Indian", ), 
new Player(148, "Chris Gayle ", "KXIP", "overseas", ), 
new Player(149, "Andrew Tye ", "KXIP", "overseas", ), 
new Player(150, "Mujeeb Ur Rahman ", "KXIP", "overseas", ), 
new Player(151, "Ravichandran Ashwin", "KXIP", "Indian", ), 
new Player(152, "Ankit Rajpoot", "KXIP", "Indian", ), 
new Player(153, "Lokesh Rahul", "KXIP", "Indian", ), 
new Player(154, "PrabhSimran Singh", "KXIP", "Indian", ), 
new Player(155, "Sarfaraz Khan", "KXIP", "Indian", ), 
new Player(156, "Agnivesh Ayachi", "KXIP", "Indian", ), 
new Player(157, "Harpreet Brar", "KXIP", "Indian", ), 
new Player(158, "Moises Henriques ", "KXIP", "overseas", ), 
new Player(159, "Arshdeep Singh", "KXIP", "Indian", ), 
new Player(160, "Darshan Nalkande", "KXIP", "Indian", ), 
new Player(161, "Murugan Ashwin", "KXIP", "Indian", ), 
new Player(162, "Varun Chakravarthy", "KXIP", "Indian", ), 
new Player(163, "Hardus Viljoen ", "KXIP", "overseas", ), 
new Player(164, "Mohammed Shami", "KXIP", "Indian", ), 
new Player(165, "Sam Curran ", "KXIP", "overseas", ), 
new Player(166, "Nicholas Pooran ", "KXIP", "overseas", ), 
new Player(167, "Mandeep Singh", "KXIP", "Indian", )
, 
new Player(168, "David Warner ", "SRH", "overseas", ), 
new Player(169, "Bhuvneshwar Kumar", "SRH", "Indian", ), 
new Player(170, "Rashid Khan ", "SRH", "overseas", ), 
new Player(171, "Deepak Hooda", "SRH", "Indian", ), 
new Player(172, "Ricky Bhui", "SRH", "Indian", ), 
new Player(173, "Manish Pandey", "SRH", "Indian", ), 
new Player(174, "Kane Williamson ", "SRH", "overseas", ), 
new Player(175, "Yusuf Pathan", "SRH", "Indian", ), 
new Player(176, "Shakib Al Hasan ", "SRH", "overseas", ), 
new Player(177, "Billy Stanlake ", "SRH", "overseas", ), 
new Player(178, "Sandeep Sharma", "SRH", "Indian", ), 
new Player(179, "Khaleel Ahmed", "SRH", "Indian", ), 
new Player(180, "Siddarth Kaul", "SRH", "Indian", ), 
new Player(181, "T Natarajan", "SRH", "Indian", ), 
new Player(182, "Basil Thampi", "SRH", "Indian", ), 
new Player(183, "Mohammad Nabi ", "SRH", "overseas", ), 
new Player(184, "Shreevats Goswami", "SRH", "Indian", ), 
new Player(185, "Wriddhiman Saha", "SRH", "Indian", ), 
new Player(186, "Martin Guptill ", "SRH", "overseas", ), 
new Player(187, "Abhishek Sharma", "SRH", "Indian", ), 
new Player(188, "Vijay Shankar", "SRH", "Indian", ), 
new Player(189, "Shahbaz Nadeem", "SRH", "Indian", ), 
new Player(190, "Jonny Bairstow ", "SRH", "overseas", ), 
new Player(191, "Sandeep Warrior ", "KKR", "Indian", )
]